Mixins
pennersr/django-allauth pull request #2158
Opened 2018-12-03 13:12 UTC by simo97

feat(account): Added a new mixins to  enable email verification control on a class-based views.

2019-08-07 17:13 UTC, simo97 commented
Oh ok will change that quickly.

2023-07-12 16:19 UTC, pennersr requested changes

2023-07-12 16:19 UTC, pennersr commented on allauth/account/mixins.py
> +It is used like django's LoginRequiedMixin, so when using this
```suggestion
It is used like django's LoginRequiredMixin, so when using this
```

2023-07-12 16:19 UTC, pennersr commented on allauth/account/mixins.py
> +there is no need to use LoginRequiedMixin fro django
```suggestion
there is no need to use LoginRequiredMixin fro django
```

2023-07-12 16:19 UTC, pennersr commented on docs/decorators.rst
> +any class-based view from django, you can use it as follow ::
```suggestion
any class-based view from django, you can use it as follows ::
```

2023-07-12 16:19 UTC, pennersr commented on docs/decorators.rst
> +    class YouClassName(VerifiedEmailRequiredMixin, ListView):
```suggestion
    class YourClassName(VerifiedEmailRequiredMixin, ListView):
```

2023-08-12 18:08 UTC, pennersr requested changes

2023-08-12 18:08 UTC, pennersr commented on allauth/account/mixins.py
> +there is no need to use LoginRequiredMixin fro django
```suggestion
there is no need to use LoginRequiredMixin from Django
```

2023-08-12 18:08 UTC, pennersr commented on allauth/account/mixins.py
> +It is used like django's LoginRequiredMixin, so when using this
```suggestion
It is used like Django's LoginRequiredMixin, so when using this
```

2023-08-25 20:14 UTC, closed without merging