Apple login bug fixes
pennersr/django-allauth pull request #2622
Opened 2020-08-04 16:17 UTC by AnsonShaji1

# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must be 100% pep8 and isort clean.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] Feel free to add yourself to `AUTHORS`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2020-08-04 19:31 UTC, bcarradini commented
Does this have any relationship to https://github.com/pennersr/django-allauth/pull/2424?

2020-08-06 06:07 UTC, AnsonShaji1 commented
Hi,
   We are using allauth version 24.0.1. Because our system has django 1.9
support.  I modify that code.I am trying for implement apple login in that
version.

Regards
Anson

On Wed, Aug 5, 2020 at 1:01 AM Barbara Carradini <notifications@github.com>
wrote:

> Does this have any relationship to #2424
> <https://github.com/pennersr/django-allauth/pull/2424>?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pennersr/django-allauth/pull/2622#issuecomment-668783597>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFHUPYQK6T3VT5HSLE5A4D3R7BOZVANCNFSM4PUSF6GA>
> .
>

2020-08-06 15:09 UTC, bcarradini commented
Oh, wow. Well... good luck!

2020-09-09 13:20 UTC, kelkarajay requested changes

2020-09-09 13:20 UTC, kelkarajay commented on allauth/socialaccount/migrations/0001_initial.py
> -                ('uid', models.CharField(max_length=255, verbose_name='uid')),
These changes should be introduced in a new migration version

2020-10-04 13:17 UTC, pennersr commented
Apple sign in has just been merged via 16e9c61102de46a52d6c51e7b63fed22865eadb7.

2020-10-04 13:17 UTC, closed without merging