feat(login ajax view): add available social providers to ajax response data
pennersr/django-allauth pull request #2650
Opened 2020-08-25 19:30 UTC by iarp

Current ajax based view lists the form and the required fields but does not list the currently enabled providers. Useful when using JS to build the page with its field and you want to add the providers.

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must be 100% pep8 and isort clean.

2020-08-25 22:30 UTC, 9mido commented
I love how you are fixing all the core issues @iarp - it is so important (more important than social aspects of the app IMO).

What do you think of issues 1872, 1307, 252, 1522, 1921, 2360? I am trying to find other core ones that could help make allauth more bulletproof.

2023-07-04 21:21 UTC, pennersr requested changes

2023-07-04 21:21 UTC, pennersr commented on allauth/account/views.py
> +from ..socialaccount import providers
It's best not to introduce a dependency from `account` to `socialaccount` as that will result in both modules to have a cyclic dependency upon each other.

2023-07-04 21:21 UTC, pennersr commented on allauth/account/views.py
> +            for provider in providers.registry.get_list(self.request):
In the current main branch, this should become `adapter.list_providers(request)`.

2023-07-11 00:28 UTC, closed without merging