feat(accounts): Add redirect handling to /accounts/social SignupView
pennersr/django-allauth pull request #3099
Opened 2022-05-24 23:34 UTC by denisemauldin

# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2022-05-25 01:14 UTC, denisemauldin commented
@pennersr Not sure if tests are necessary, but happy to write some based off suggestions.

2023-10-13 12:10 UTC, pennersr commented
When the form is valid, the social signup view ends with a call to: `helpers.complete_social_signup()`.  Inside that method, the next URL stashed in the `sociallogin` is already used (`sociallogin.get_redirect_url(request)`), which is identical to the `next = sociallogin.state.get(REDIRECT_FIELD_NAME, None)` call that you are adding. So redirects should already be properly be handled. if not, then we definitely could use a test case to expose the problem you are trying to address here.

2023-10-13 12:12 UTC, pennersr requested changes

2023-10-13 12:12 UTC, pennersr commented on allauth/socialaccount/helpers.py
> +        next = sociallogin.state.get(REDIRECT_FIELD_NAME, None)
Why not call `sociallogin.get_redirect_url(request)`?

2023-10-13 12:12 UTC, pennersr commented on allauth/socialaccount/helpers.py
> +                url, REDIRECT_FIELD_NAME, next
This would need `urlencode()`'ing

2023-12-15 22:13 UTC, closed without merging