chore(oauth): show an informative log when OAuthError is raised
pennersr/django-allauth pull request #3184
Opened 2022-11-11 07:31 UTC by ykdojo

This is similar to the way facebook/views.py logs an exception.

This feature was requested on https://github.com/pennersr/django-allauth/issues/2142.

The original (closed) PR: https://github.com/pennersr/django-allauth/pull/2175

Sample log:
```
Error processing OAuth
Traceback (most recent call last):
  File "/Users/ykdojo/Desktop/django-allauth/allauth/socialaccount/providers/oauth/views.py", line 79, in login
    return client.get_redirect(auth_url, auth_params)
  File "/Users/ykdojo/Desktop/django-allauth/allauth/socialaccount/providers/oauth/client.py", line 157, in get_redirect
    request_token = self._get_request_token()
  File "/Users/ykdojo/Desktop/django-allauth/allauth/socialaccount/providers/oauth/client.py", line 84, in _get_request_token
    raise OAuthError(
allauth.socialaccount.providers.oauth.client.OAuthError: Invalid response while obtaining request token from api.twitter.com. Response text: <?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
```

# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2022-12-29 20:51 UTC, pennersr requested changes

2022-12-29 20:51 UTC, pennersr commented on allauth/socialaccount/providers/oauth/client.py
> +                         f"{get_token_prefix(self.request_token_url)}. " +
**Issue**: Using f-strings breaks the python 3.5 build.

2022-12-29 20:51 UTC, pennersr commented on allauth/socialaccount/providers/oauth/views.py
> +            logger.exception('Error processing OAuth')
**Issue**:  From a logging perspective, these errors can occur in production and don't necessarily indicate exceptional situations that need direct attention. Hence, I think we need to use the regular `error` level.

```suggestion
            logger.error("OAuth authentication error", exc_info=True)
```

2023-08-02 08:00 UTC, katomaso commented
Please @ykdojo , could you move on with that? I personally think it is very important to have logging of errors

2023-08-25 17:03 UTC, varunsaral commented
can i take up the work @pennersr ?

2023-08-25 17:41 UTC, pennersr commented
@varunsaral Of course, this one seems to be abandoned... thanks.

2023-08-31 12:18 UTC, varunsaral commented
@pennersr this can be closed, fixed by #3392

2023-08-31 13:00 UTC, closed without merging