feat(provider): Add provider Calendly
pennersr/django-allauth pull request #3249
Opened 2023-02-03 11:13 UTC by ghassen-create

# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2023-02-10 16:01 UTC, pennersr requested changes

2023-02-10 16:01 UTC, pennersr commented on allauth/socialaccount/providers/calendly/views.py
> +        print(resp.json())
**Issue**: :printer:

2023-02-10 16:01 UTC, pennersr commented on docs/overview.rst
> +- CALENDLY (OAuth2)
```suggestion
- Calendly (OAuth2)
```

2023-02-10 16:01 UTC, pennersr commented on docs/providers.rst
> +CALENDLY
```suggestion
Calendly
```

2023-02-10 16:01 UTC, pennersr commented on docs/providers.rst
> +CALENDLY OAuth2 Documentation
```suggestion
Calendly OAuth2 Documentation
```

2023-02-12 19:31 UTC, pennersr commented
Can you have a look -- the test suite is failing.

2023-02-13 11:37 UTC, ghassen-create commented
i am not able find an issue -- have a check now

2023-07-11 20:27 UTC, closed without merging