fix(google): Fixed bug where get_avatar_url sometimes returns None
pennersr/django-allauth pull request #3574
Opened 2023-12-20 02:37 UTC by arowley-ai

# Summary
The provider is configured to rely on data decoded from the JWT for populating the user details. This results in a situation where, for certain users, `get_avatar_url` returns `None` because the photo URL field is not always included in the JWT. An alternative approach is to hit the userinfo API, which consistently provides the user data across all accounts. The existing default permissions are sufficient to query this endpoint.

# Detail
The provider is currently configured to rely on data decoded from the JWT used in the login process for populating the user photo URL and other user attributes.

## User Photos in Google
Google seems to maintain two types of user photos which we will call "public" and "private" even though both are technically publicly accessible given you have the right URL:
- Public user photo URLs contain about ~100 characters. I found that my personal Gmail account had a public photo URL.
- Private user photo URLs are much longer and contain ~1000 characters. I think this is done to make them harder to discover. I found that my paid-for G Suite account had a private photo URL.

## JWT return values
I was able to establish via the Google OAuth 2 playground that the information encoded in a JWT differs based on the type of photo URL that an account has, such that:
- For public user photos, the returned JWT includes the user photo URL.
- For private user photos, the returned JWT does not include the user photo URL. Presumably, that is done to keep the overall size of the JWT down. 

Therefore, under the current approach, the user photo is inconsistently populated depending on what type of profile photo the user has.

## Alternative appraoch to accessing user details
I was also able to establish that the current default permissions for the Google provider are sufficient to actually access the photo URL of each user, but doing so requires hitting the relevant "user.info" endpoint, which is "https://www.googleapis.com/oauth2/v2/userinfo." My view is that any field that is reasonably needed by Django All-Auth can be gained by hitting this endpoint and so I have commented out the existing code. 

# Conclusion 
This pull request changes the methodology used at login to grab the user details from the relevant endpoint instead of by decoding the JWT. I welcome any debate or feedback on this issue that is needed before this PR can be merged.

## Acknowledgement
Thank you so much for maintaining and providing such great open source software.

2023-12-20 20:52 UTC, pennersr commented
Thanks for tracking this issue down and the detailed analysis. I would expect projects that are dependent on the avatar URL to be in the minority. That, and the fact that fetching userinfo introduces overhead as it results in an additional roundtrip, I would prefer to have this behavior configurable using a setting that is default off. How about:

```
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "FETCH_USERINFO": True,
        ...
```

2023-12-21 02:45 UTC, arowley-ai commented
>I would prefer to have this behavior configurable using a setting that is default off. 

Thanks @pennersr for the reply. Two questions:

1. If the setting is on but the original JWT includes the avatar URL should we skip the call to getinfo? I would think yes, since at that point it's unnecessary. 
2. If the user isn't aware of this setting and has a situation where get_avatar_url returns None would you want any kind of warning that indicates that they should enable this setting in order to return the avatar URL properly?

2023-12-22 10:46 UTC, pennersr requested changes

2023-12-22 10:46 UTC, pennersr commented on allauth/socialaccount/providers/google/views.py
> +            if resp.status_code != 200:
```suggestion
            if not resp.ok:
```

2024-01-05 15:28 UTC, pennersr commented
Thanks! Merged via 89ebcc5e

2024-01-05 15:28 UTC, closed without merging