docs(socialaccount): add config example for Authelia
pennersr/django-allauth pull request #3652
Opened 2024-02-21 19:08 UTC by noantiq

# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers/<provider name>.rst` and `docs/providers/index.rst` Provider Specifics toctree.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2024-02-21 19:14 UTC, noantiq commented
I struggled a bit to figure out the correct config values to use on each site when setting up https://github.com/paperless-ngx/paperless-ngx with https://github.com/authelia/authelia using OIDC. Hopefully this can be helpful for someone.

2024-02-25 14:35 UTC, pennersr requested changes

2024-02-25 14:35 UTC, pennersr commented on docs/socialaccount/providers/authelia.rst
> +An example configuration for authelia would look like this:
```suggestion
An example configuration for authelia would look like this::
```

2024-02-25 14:35 UTC, pennersr commented on docs/socialaccount/providers/authelia.rst
> +::
```suggestion
```

2024-02-25 14:36 UTC, pennersr commented
Question, there is this open ticket:

https://github.com/pennersr/django-allauth/issues/3631

Is Authelia working for you? Why isn't that ticket causing trouble for you?

2024-02-25 23:00 UTC, noantiq commented
Yes, it’s working for me. The stable version as well as the newest beta.

2024-04-21 09:51 UTC, merged