Feature: Add Lichess Provider
pennersr/django-allauth pull request #3743
Opened 2024-04-23 02:38 UTC by brandon-kong

# Submitting Pull Requests

## General

 - [x] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [x] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [x] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [x] If your changes are significant, please update `ChangeLog.rst`.
 - [x] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [x] Make sure unit tests are available.
- [x] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [x] Add documentation to `docs/providers/<provider name>.rst` and `docs/providers/index.rst` Provider Specifics toctree.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

2024-04-23 05:49 UTC, pennersr requested changes

2024-04-23 05:49 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +        email_data = (
This is an additional call that is only needed if this is true:

```
from allauth.socialaccount.app_settings import QUERY_EMAIL
```

Can you make that optional?

2024-04-23 05:49 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +
Can you please add `raise_for_status()` here, so something like:

```
resp = ...get(...)
resp.raise_for_status()
extra_data = resp.json()
```

2024-04-23 05:49 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +            .get(
Can you add `raise_for_status()` here as well.

2024-04-23 05:49 UTC, pennersr commented on allauth/socialaccount/providers/lichess/provider.py
> +        verified = data.get("verified") or False
While there seems to be a `verified` flag over at https://lichess.org/api#tag/Account/operation/accountMe it is not documented what that means. It is also not listed at the email endpoint, so we really cannot tell with confidence that this really implies that the email address is verified. I don't think we can rely on this.

2024-04-23 20:54 UTC, brandon-kong commented
@pennersr Thank you for your feedback. I went ahead and applied the changes you requested.

2024-04-24 07:43 UTC, pennersr requested changes

2024-04-24 07:43 UTC, pennersr commented on ChangeLog.rst
> +- Added a new provider, Atlassian, Lichess
Can you put this below the 0.63.0 heading?

2024-04-24 07:43 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +    access_token_url = "{0}/api/token".format(provider_base_url)
```suggestion
    access_token_url = f"{provider_base_url}/api/token"
```

2024-04-24 07:43 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +    authorize_url = "{0}/oauth".format(provider_base_url)
```suggestion
    authorize_url = f"{provider_base_url}/oauth"
```

2024-04-24 07:43 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +    email_address_url = "{0}/api/account/email".format(provider_base_url)
```suggestion
    email_address_url = f"{provider_base_url}/api/account/email"
```

2024-04-24 07:43 UTC, pennersr commented on allauth/socialaccount/providers/lichess/views.py
> +    profile_url = "{0}/api/account".format(provider_base_url)
```suggestion
    profile_url = f"{provider_base_url}/api/account"
```

2024-04-24 19:55 UTC, pennersr commented
Merged via 28e733bc

2024-04-24 19:55 UTC, closed without merging