fix(mfa): Add types to `allauth.mfa` flows
pennersr/django-allauth pull request #3866
Opened 2024-06-04 12:23 UTC by akx

This PR adds a bunch of types to `allauth.mfa`'s internals.

Our app needs to set up MFA with a slightly custom flow, so we can't use the forms or headless features, so I needed to delve a bit into how things work under the hood, and figured it'd be useful if types were documented technically too, for IDEs etc.

Feels like `TOTP` and `RecoveryCodes` should have a superclass, but that's beyond the scope of this PR...

2024-06-11 20:46 UTC, pennersr requested changes

2024-06-11 20:46 UTC, pennersr commented on allauth/mfa/models.py
> +    def delete_dangling_recovery_codes(self, user) -> "Authenticator":
**Issue**: This can also return `None`.

2024-06-11 20:46 UTC, pennersr commented on allauth/mfa/recovery_codes.py
> +    def _validate_migrated_code(self, code: str) -> bool:
**Issue**: Returns `None` as well.

2024-06-19 14:10 UTC, akx commented
> Can you please rebase? Thanks.

Done, let's see if it passes! 🤞 

> adding type hints without enforcing them easily leads to errors.

Tangentially: I know we've talked about Ruff before and I know how you feel about it, but it was pretty useful here, as the [ANN series](https://docs.astral.sh/ruff/rules/#flake8-annotations-ann) of rules can narrow down places that are missing annotations, and a human can then figure them out.

2024-06-19 14:56 UTC, pennersr commented
See #3905 -- some of your changes are not Python 3.7 compatible, that will be addressed by #3905.

2024-06-20 05:29 UTC, akx commented
@pennersr On that note, what's your stance on using `from __future__ import annotations` and futuristic annotations (e.g. `list[Foo] | None`)? I don't think anything in allauth is expecting to introspect annotations (where unevaluated futured annotations could be an issue).

2024-06-20 06:21 UTC, merged